port: 8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  name: db_anv
jwt:
  secret: anhvanhoa
  expiration: 3600

mailserver:
  - host: smtp.gmail.com
    port: 587
    username: toplaiphaiwin@gmail.com
    email: toplaiphaiwin@gmail.com
    password: 123456