port: 8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  name: db_anv
jwt:
  secret: anhvanhoa
  expiration: 3600
cors:
  origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:8080
    - http://vananh.com:3000
  methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
  headers: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  credentials: true
  maxAge: 3600
mailserver:
  - host: smtp.gmail.com
    port: 587
    username: toplaiphaiwin@gmail.com
    email: toplaiphaiwin@gmail.com
    password: ydhw abgh wwen mkqx
    nameProvider: Ánh Văn Hóa

mailSender: toplaiphaiwin@gmail.com

hostClient: http://localhost:3000